apiVersion: v1
kind: Service
metadata:
  name: monitoringsystem-service
spec:
  selector:
    app: monitoringsystem
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
  - name: secondary-port
    protocol: TCP
    port: 81
    targetPort: 8081
  type: LoadBalancer
